# 1. Understanding the Core Concept Perfectly

# 2. Top 1% Best Practice Tasks (NLP & Data Analysis Focus)

### Part A: Speed & Structure (Level 1)

In [2]:
import numpy as np

In [2]:
# 1. The List Challenge: Recreate the time comparison from your notebook. Compare a Python list and a NumPy array of 1,000,000 elements for a 
# cubing operation ($x^3$). Record the time difference.

import time

elements = 1000000
python_list = list(range(elements))
np_array = np.arange(elements)

start_list = time.time()
list_cube = [x**3 for x in python_list]
end_list = time.time()
final_list_time = end_list - start_list 

start_array = time.time()
array_cube = np_array**3
end_array = time.time()
final_array_time = end_array - start_array

print(f"Total time taken for list is : {final_list_time} seconds")
print(f"Total time taken for array is : {final_array_time} seconds")
print(f"Difference is : {final_list_time - final_array_time} seconds")
print(f"NumPy is {final_list_time / final_array_time:.2f}x faster!")

Total time taken for list is : 0.5221953392028809 seconds
Total time taken for array is : 0.009016275405883789 seconds
Difference is : 0.5131790637969971 seconds
NumPy is 57.92x faster!


In [3]:
# 2. Identity Matrix: Create a 5x5 identity matrix using np.eye(). Why is this useful in linear algebra?
matrix = np.eye(5)
matrix

# numpy.eye() is a function in the NumPy library that creates a 2D array with ones on the diagonal and zeros elsewhere. 
#This function is often used to generate identity matrices with ones along the diagonal and zeros in all other positions.'''

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# 3. Specific Linspace: Generate exactly 100 values between 0 and 50 using np.linspace().
# linspace (short for linear space) is a NumPy function that generates a sequence of evenly spaced numbers over a specified interval
# np.linspace(start, stop, num)

linspace_nums = np.linspace(0, 50, 100)
linspace_nums

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [11]:
# 4. Reshaping: Create a 1D array of 20 elements and use .reshape(4, 5) to turn it into a 2D matrix.
# reshape() is a built-in NumPy method used to change the dimensions (shape) of an array without changing its actual data.
# array.reshape(rows, columns)

array_1d = np.arange(20)
print("Original 1D array \n")
print(array_1d)

array_2d = array_1d.reshape(4, 5)
print("Reshaped 2D array \n")
print(array_2d)

Original 1D array 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped 2D array 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
# 5. Random Noise: Use np.random.rand(10, 10) to create a matrix of random decimals. This simulates "noise" in signal processing.

matrix = np.random.rand(10, 10)
matrix

# Signal Processing ApplicationIn actual data pipelines, you would use this matrix to evaluate filter algorithms. For example, 
# adding this exact noise matrix to a clean image array or audio wave lets you benchmark how effectively your code strips away background interference.

array([[0.5401611 , 0.36469633, 0.83198089, 0.16800756, 0.27893389,
        0.79253195, 0.30552269, 0.72948572, 0.31404406, 0.7901301 ],
       [0.59723167, 0.94624769, 0.66902231, 0.20997026, 0.72835738,
        0.25630258, 0.90838542, 0.10335036, 0.23435163, 0.92620162],
       [0.70936991, 0.27866803, 0.6695698 , 0.25333502, 0.58021104,
        0.65021608, 0.43470592, 0.88254942, 0.79055639, 0.14404025],
       [0.16726416, 0.12372374, 0.72541735, 0.81545898, 0.95101519,
        0.45204394, 0.98769862, 0.0959062 , 0.92812329, 0.64165676],
       [0.82486072, 0.0865695 , 0.62544313, 0.00365226, 0.60957031,
        0.98065299, 0.49094474, 0.51381879, 0.04595974, 0.81397565],
       [0.23642427, 0.83691509, 0.74178511, 0.26182899, 0.90749725,
        0.93844948, 0.35390079, 0.00906863, 0.85397174, 0.35211253],
       [0.37396636, 0.40079623, 0.35895739, 0.62055243, 0.04752031,
        0.10326168, 0.00302081, 0.65546039, 0.3957261 , 0.25885898],
       [0.68089198, 0.62833364, 0.2156043

### Part B: Advanced Indexing & Math (Level 2)

In [18]:
# 6. Boolean Indexing (Critical for NLP): Given arr = np.array([10, 50, 20, 80, 5]), write a one-liner to return only numbers greater than 30.
arr = np.array([10, 50, 20, 80, 5])
result = arr[arr > 30]
print(result)

[50 80]


In [26]:
# 7. Slicing 2D Arrays: From a 3x3 matrix, extract only the middle column.
matrix = np.array([[[1, 2, 3],[4,5,6],[7,8,9]]])
print(matrix)

print("\n\nMiddle column : ")
print(matrix[:, 1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Middle column : 
[[4 5 6]]


In [39]:
# 8. Normalization: Given a sales array, subtract the average from every element and divide by the standard deviation. This is a common "Scaling" 
# technique in Machine Learning.

products = ['Lapotp', 'Phones', 'SmartPhones', 'Computer']
sales_array = np.array([80, 50, 60, 56], dtype = float)
print(sales_array)

avg = np.mean(sales_array)
#avg = np.average(sales_array)

# standard deviation
sd = np.std(sales_array)

normalized = (sales_array - avg) / sd
print(f"Average : {avg:.2f}")
print(f"Standard Deviation : {sd:.2f}")
print(f"Final array is : {normalized}")

[80. 50. 60. 56.]
Average : 61.50
Standard Deviation : 11.26
Final array is : [ 1.64322769 -1.02146586 -0.13323468 -0.48852715]


In [5]:
# 9. Horizontal/Vertical Stacking: Research np.hstack() and np.vstack(). Combine two matrices together.
# In Python, np.hstack() and np.vstack() are NumPy library functions used to join multiple arrays together by stacking them along different axes.
# np.hstack() stands for horizontal stack; it joins arrays side-by-side (column-wise).
# np.vstack() stands for vertical stack; it joins arrays on top of each other (row-wise).

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[6, 7], [8, 9]])

horizontal = np.hstack((matrix1, matrix2))
vertical = np.vstack((matrix1, matrix2))

print("Horizontal Stack \n: ", horizontal)
print("\n\nVertical Stack \n: ", vertical)

Horizontal Stack 
:  [[1 2 6 7]
 [3 4 8 9]]


Vertical Stack 
:  [[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [11]:
# 10. Finding Extremes: Find the index of the maximum value in an array using np.argmax().
# np.argmax() is a NumPy function that returns the index (position) of the largest value in an array.
matrix = np.array([[10, 20, 90], [95, 63, 78], [100, 56, 85]])
index = np.argmax(matrix)
print("Maximum value index is : ", index)

Maximum value index is :  6


### Part C: Building Future NLP Logic (Level 3)

In [8]:
# 11. Word Vector Simulation: Create a 10x300 matrix representing 10 words, each with a 300-dimension vector. Calculate the average vector of all 10 words.


In [9]:
# 12. Binary Transformation: Use np.where() to turn all values in an array into 1 if they are positive and 0 if they are negative.


In [9]:
# 13. Dot Product: Research np.dot(). Perform a dot product between a 2x3 and a 3x2 matrix. This is the core of "Attention Mechanisms" in NLP models.


In [9]:
# 14. Saving Data: Save a large NumPy array to a .npy file and load it back. Why is this faster than saving to a .txt?


In [9]:
# 15. Broadcasting: Create a 1D array of 3 elements and add it to a 3x3 matrix. Observe how NumPy “stretches” the data automatically.


# Part D: Expert “Pune-Listing” Challenges (Level 4)

In [9]:
# 16. Missing Data Handling: Use np.nan to represent missing values and calculate the sum while ignoring them (np.nansum).

In [9]:
# 17. Frequency Count: Use np.unique(arr, return_counts=True) to find how many times each word ID appears in a simulated text corpus.

In [9]:
# 18. Distance Calculation: Calculate the Euclidean distance between two vectors using only NumPy math functions ($sqrt(sum((a-b)^2))$).

In [9]:
# 19. Efficient Sorting: Use np.argsort() to get the indices that would sort an array, rather than sorting the array itself.

In [9]:
# 20. Logic Challenge: Create a function that takes a matrix and replaces all values on the diagonal with their square root.